[package]
name = "libm-bench"
version = "0.1.0"
authors = ["Gonzalo Brito Gadeschi <gonzalobg88@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
libm = { path = "../..", default-features = false }
rand = "0.8.5"
paste = "1.0.15"

[features]
default = []
unstable = [ "libm/unstable" ]
